Fixed Can only reserve up to Quantitiy in Cart and other minor errors from merge
Qihuiwang3/JID-4121-LMCFilm pull request #109
Opened 2024-11-26 22:53 UTC by weswilson24

Can now add up to the quantity of the item in cart

Fixed some minor errors didnt see when merging from main:

-Reservation history table order needed to be reversed
-view bar code and view detail popup code somehow got altered on the reservation history table, tiny quick fixes to make it completely work again

2024-11-29 17:37 UTC, mengzhuou commented
In ReservationHistory page, the view details modal should be up to date with what's in the database. But it's not.
To be more specific, I made an order and checked out equipment. I can see my checkout record on ViewReservation page but cannot see the record on ReservationHistory page. 

<img width="859" alt="image" src="https://github.com/user-attachments/assets/fd4d38cc-ab9a-4fa4-afab-9bcbbeab08b4">
<img width="886" alt="image" src="https://github.com/user-attachments/assets/53f6dbd7-f87b-4b4d-b774-ece82d17bf09">

2024-11-29 17:40 UTC, mengzhuou requested changes
1. In ReservationHistory page, the view details modal should be up to date with what's in the database. But it's not.
To be more specific, I made an order and checked out equipment. I can see my checkout record on ViewReservation page but cannot see the record on ReservationHistory page. 

<img width="859" alt="image" src="https://github.com/user-attachments/assets/fd4d38cc-ab9a-4fa4-afab-9bcbbeab08b4">
<img width="886" alt="image" src="https://github.com/user-attachments/assets/53f6dbd7-f87b-4b4d-b774-ece82d17bf09">


2. CSS does not look like this before

<img width="524" alt="image" src="https://github.com/user-attachments/assets/4d6990e1-d0fa-4c87-8765-4d9aebeae328">

2024-12-01 20:01 UTC, mengzhuou approved these changes

2024-12-01 20:06 UTC, Xisheng0725 approved these changes

2024-12-01 20:06 UTC, merged