Scrum 149: BUG fix for Student and Equipment page
Qihuiwang3/JID-4121-LMCFilm pull request #58
Opened 2024-10-04 04:52 UTC by mengzhuou

1. http://localhost:3000/Students
2. http://localhost:3000/Equipment
3. Removed Edit Button folder
4. Removed Edit Mode and Save button, the functionalities for delete and change role, etc, are all worked.

<img width="952" alt="image" src="https://github.com/user-attachments/assets/eb817f66-92ff-4211-bcdc-dcaa56c11b11">

2024-10-04 20:19 UTC, Xisheng0725 requested changes
could u please using the button component in student portal to make sure abutton style is same with student portal

2024-10-04 22:13 UTC, mengzhuou commented
> could u please using the button component in student portal to make sure abutton style is same with student portal

1. Just replaced it with Button component
2. Adjusted the css for Table columns
3. Fixed the bug that the table result is now consistent with search result before and after switching role

2024-10-05 15:43 UTC, Xisheng0725 approved these changes

2024-10-07 15:30 UTC, Xisheng0725 approved these changes

2024-10-09 21:07 UTC, denialpan approved these changes
Looks good, you can merge this

2024-10-10 22:05 UTC, merged