scrum-188
Qihuiwang3/JID-4121-LMCFilm pull request #93
Opened 2024-11-08 02:13 UTC by mengzhuou

Make Search Button not Disabled before search. Radio button should be deleted.

https://qihui1002.atlassian.net/jira/software/projects/SCRUM/boards/1?assignee=712020%3A7b04f5e4-5741-48aa-8369-3407eba9e295&selectedIssue=SCRUM-188

2024-11-08 02:27 UTC, Qihuiwang3 approved these changes

2024-11-08 04:00 UTC, Xisheng0725 requested changes
should check the item id

2024-11-08 16:35 UTC, Xisheng0725 approved these changes

2024-11-08 16:36 UTC, Xisheng0725 requested changes
should check the item id

2024-11-08 23:46 UTC, mengzhuou commented
> should check the item id

issue fixed

2024-11-09 21:14 UTC, Xisheng0725 approved these changes

2024-11-09 21:14 UTC, merged